store/urls.py
from django.conf.urls.defaults import *
# Uncomment the next two lines to enable the admin:

urlpatterns = patterns('',
   url(r'^store/edit-store/$','store.views.edit_store',name='edit_store'),
   url(r'^store/add-store/$','store.views.add_store',name='add_store'),
   url(r'^store/$','store.views.view_store',name='view_store'),
   url(r'^find-by-store/$','store.views.list_store',name='list_store'),
   url(r'^find-by-designer/$','store.views.list_designer',name='list_designer'),
   url(r'^find-by-store/(?P<type>[-\w]+)/(?P<alphabet>[-\w]*)/*$','store.views.list_store',name='list_store2'),
   url(r'^find-by-item/$','store.views.list_item',name='list_item'),
   
   url(r'^store/remove-store/$','store.views.remove_store',name='remove_store'),
   url(r'^store/comment/(?P<slug>[-\w]*)/(?P<store_id>\d*)/$','store.views.view_comment',name='view_comment'),
   url(r'^store/remove_comment/(?P<comment_id>\d+)/$','store.views.remove_comment',name='remove_comment'),
   url(r'^store/(?P<user_id>\d+)/add/$','store.views.addicted',name='addicted'),
   url(r'^store/add-item/(?P<line_id>\d+)/$','store.views.item_add',name='item_add'),
   url(r'^store/(?P<item_id>\d+)/add-item-complete/$','store.views.add_item_complete',name='add_item_complete'),
   url(r'^store/view-item/(?P<line_id>\d+)/$','store.views.view_item',name='view_item'),
   url(r'^store/view-collection/(?P<line_name>[-\w]+)/$','store.views.view_same_collection',name='same_collection'),
   url(r'^store/edit-item/(?P<line_id>\d+)/$','store.views.edit_item',name='edit_item'),
   url(r'^store/detail-items/(?P<item_id>\d+)/$','store.views.redir_detail_item',name='detail_items'),
   url(r'^store/detail-items/(?P<item_id>\d+)/(?P<item_slug>[-\w]+)/$','store.views.detail_items',name='item_info'),
   url(r'^store/remove-line/(?P<item_id>\d+)/$','store.views.remove_item',name='remove_item'),
   url(r'^store/remove-item/(?P<item_id>\d+)/$','store.views.remove_item2',name='remove_item2'),
   url(r'^store/add-line/$','store.views.line_add',name='line_add'),
   url(r'^store/edit-line/(?P<line_id>\d+)/$','store.views.edit_line',name='edit_line'),
   url(r'^store/view-line/(?P<store_id>\d+)/$','store.views.view_line',name='view_line'),
   url(r'^store/view-my-addict/(?P<store_id>\d+)/$','store.views.view_my_addict',name='view_my_addict'),
   url(r'^store/view-addicts-to/$','store.views.addicts_to',name='addicts_to'),
   url(r'^store/remove-addicts-to/(?P<addict_id>\d+)/$','store.views.remove_addict',name='remove_addict'),
   url(r'^store/add-compare-item/(?P<item_id>\d+)/$','store.views.add_compare_item',name='compare_item'),
   url(r'^store/view-compare-list/$','store.views.view_compare_list',name='view_compare_list'),
   url(r'^store/view-compare-thumbnails/$','store.views.view_compare_thumbnails',name='view_compare_thumbnails'),
   url(r'^store/remove-compare-list/$','store.views.remove_compare_list',name='remove_compare_list'),
   url(r'^store/remove-compare-thumbnails/$','store.views.remove_compare_thumbnails',name='remove_compare_thumbnails'),
   url(r'^store/view-detail-compare/$','store.views.view_detail_compare',name='view_detail_compare'),
   url(r'^store/view-detail-compares/$','store.views.view_detail_compares',name='view_detail_compares'),
   url(r'^store/primary-picture/(?P<line_id>\d+)/$','store.views.primary_picture',name='primary_picture'),
   url(r'^most/(?P<choose_slug>[-\w]+)/(?P<slug>[-\w]+)/(?P<type>[-\w]*)/*$','store.views.view_most_all',name='view_most_all'),
   url(r'^store/most/(?P<store_type>[-\w]+)/(?P<store_slug>[-\w]+)/$','store.views.view_most_store',name='view_most_store'),
   url(r'^items/(?P<item_slug>[-\w]+)/$','store.views.view_most_item',name='view_most_item'),
   url(r'^store/rate-store/(?P<store_id>\d+)/$','store.views.rate_store',name='rate_store'),
   url(r'^store/rate-item/(?P<item_id>\d+)/$','store.views.rate_item',name='rate_item'),
   url(r'^store/message/(?P<item_id>\d+)/$','store.views.message_fashion_owner',name='message_fashion_owner'),
   url(r'^(?P<store_id>\d+)/store-notice/$','store.views.store_notice',name='notice_store'),
   url(r'^(?P<item_id>\d+)/item-notice/$','store.views.item_notice',name='notice_item'),
   url(r'^store/remove_line/$','store.views.delete_line',name='remove_line'),
   url(r'^store/view_remove_line/$','store.views.remove_line',name='view_remove_line'),
   url(r'^store/delete-item/(?P<item_id>\d+)/$','store.views.delete_item',name='delete_item'),
   url(r'^store/remove_picture/(?P<item_id>\d+)$','store.views.remove_picture',name='remove_picture'),
   url(r'^store/remove/(?P<slug>[-\w]+)/(?P<item_id>\d*)/*$','store.views.remove',name='remove_collection_or_item'),
   url(r'^store/item/detail_picture/(?P<item_id>\d+)/(?P<slug>[-\w]+)/$','store.views.view_detail_pic',name='view_detail_pic'),
   url(r'^store/invite-friend/by-email/$','store.views.invite_friend',name='by_email'),
   url(r'^store/confirm_remove/$','store.views.confirm_remove_store',name='confirm_rem_store'),
   url(r'^report/(?P<id>\d+)/(?P<slug>[-\w]+)/$','store.views.report_content',name='report'),
   url(r'^see_all/designer/(?P<slug>[-\w]*)/*$','store.views.view_all_designer',name='view_all_designer'),
   url(r'^index/(?P<type>[-\w]+)/(?P<alphabet>[-\w]*)/*$','store.views.indexing',name='indexing'),
   url(r'^store/(?P<slug>[-\w]*)/$','store.views.view_store',name='view_stores'),
   #url(r'^$','store.views.list',name='list'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from store import urls,views
from store.sitemap import StoreSitemap,ItemSitemap,LineSitemap
from coltrane.sitemap import ColtraneSitemap

admin.autodiscover()

sitemaps = {
    "store":StoreSitemap,
    "item": ItemSitemap,
    "line":LineSitemap,
    "Coltrane":ColtraneSitemap,
}
admin.site.index_template='admin/custom_index.html'
urlpatterns = patterns('',
    # Example:
    # (r'^fashion/', include('fashion.foo.urls')),
    #(r'^fashion/', include('clothing.urls')),
    #(r'^admin/', include(admin.urls),{'SSL':True}),
    
    (r'^account/', include('accounts.urls')),
    (r'^fashion/', include('store.urls')),
    (r'^fashion-facts/', include('coltrane.urls')),
    (r'^mail/', include('mail.urls')),
    (r'^contacts/', include('contacts.urls')),
    (r'^413/$','django.views.generic.simple.direct_to_template', {'template': '413.html'}),
    (r'^site-map/','django.views.generic.simple.direct_to_template', {'template': 'sitemap.html'}),
    (r'^rss/','django.views.generic.simple.direct_to_template', {'template': 'rss.xml'}),
    (r'^pageflip/', include('pageflip.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    #(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s' % settings.MEDIA_ROOT, 'show_indexes': True}),
    #(r'^(?P<slug>[-\w]*)/*$','django.views.generic.simple.direct_to_template', {'template': 'index.html'}),
    (r'force-error', 'views.force_error'),
    
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {}, name='translation'),
    url(r'^google-results/search/','django.views.generic.simple.direct_to_template', {'template': 'google_results.html'},name="google_results"),
    url(r'^$','store.views.view_home',name='home'),
)
if settings.STATIC_MEDIA:
  #this line is so that production site does not serve static media with the line below, it is inefficient
  urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s' % settings.MEDIA_ROOT, 'show_indexes': True}),
  )
handler500='extra.views.server_error'

store/models.py
from django.db import models
from accounts.models import User,ProvinceAreaCode,PhoneAreaCode,CountryAreaCode
from django.utils.translation import ugettext_lazy as _
from datetime import datetime,date
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify,removetags,mark_safe
from store.postmarkup import render_bbcode

# Create your models here.
AVAILABILITY_CHOICE = (
(1,'In-Stock'),
(2,'Pre-Order'),
(3,'Sold Out'),
)
"""
GENDER_CHOICE = (
    (1,'MALE'),
    (0,'FEMALE'),
    )
"""
class Currency(models.Model):
    title = models.CharField(max_length=3)
    def __unicode__(self):
        return unicode('%s')%(self.title)

class LineCategory(models.Model):
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return self.name
    
class Store(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=25)
    location = models.CharField(max_length=500,blank=True)
    province = models.ForeignKey(ProvinceAreaCode,blank=True,null=True)
    post_code = models.IntegerField()
    country = models.ForeignKey(CountryAreaCode,related_name='country_code')
    phone_area = models.ForeignKey(PhoneAreaCode,related_name='phone_code',blank=True,null=True)
    telephone=models.CharField(max_length=20)
    handphone=models.CharField(max_length=20,blank=True,null=True)
    fax_code = models.ForeignKey(PhoneAreaCode,related_name='fax_code' ,blank=True,null=True)
    fax=models.CharField(max_length=20,blank=True,null=True)
    company_website = models.URLField(blank=True)
#    contacts = models.CharField(max_length=20,blank=True)
#    email = models.CharField(max_length=50,blank=True)
    store_story = models.CharField(max_length=1000,blank=True)
    picture = models.ImageField(upload_to='store/img')
    promotion_text = models.CharField(max_length=1000,null=True)
    last_updated = models.DateTimeField(default=datetime.now)
    slug = models.SlugField(unique=True,null=True,blank=True)
    deleted=models.BooleanField(default=False)
    def location_list(self):
        location_list=self.location.split('\r')
        return location_list
    def store_story_list(self):
        store_story_list=self.store_story.split('\r')
        return store_story_list
    def promotion_text_list(self):
        promotion_text_list=self.promotion_text.split('\r')
        return promotion_text_list
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('view_stores',args=(self.slug,))
#    def save(self):
#        super(Store,self).save()
#        new_line=Line(store=self,line=self.name+"'s line")
#        new_line.save()


class Line(models.Model):
    store = models.ForeignKey(Store,related_name='line_store')
    line = models.CharField(max_length=50)
    category = models.ForeignKey(LineCategory)
    slug = models.SlugField(null=True,blank=True)
    def __unicode__(self):
        return self.line
    
    def get_absolute_url(self):
        return reverse('view_line',args=(self.store.pk,))
    
    def save(self):
        self.slug=slugify(self.line)
        super(Line,self).save()

class Item(models.Model):
    IN_STOCK = 1
    PRE_ORDER = 2
    SOLD_OUT = 3
    MALE = 1
    FEMALE = 0
    UNISEX = 2
    AVAILABILITY_CHOICE = (
    (IN_STOCK,'In-Stock'),
    (PRE_ORDER,'Pre-Order'),
    (SOLD_OUT,'Sold Out')
    )
    GENDER_CHOICE = (
    (MALE,'MALE'),
    (FEMALE,'FEMALE'),
    (UNISEX,'UNISEX'),
    )
    line = models.ForeignKey(Line)
    item = models.CharField(max_length=100)
    description = models.CharField(max_length=1000,blank=True)
    colour = models.CharField(max_length=30,blank=True)
    size = models.CharField(max_length=30,blank=True)
    gender = models.IntegerField(choices=GENDER_CHOICE,blank=True,null=True)
    currency = models.ForeignKey(Currency,null=True)
    price = models.IntegerField(max_length=9,default=0)
    #price_request = models.BooleanField(default=False,blank=True)
    availability = models.IntegerField(choices=AVAILABILITY_CHOICE,default=IN_STOCK)
    picture1 = models.ImageField(_(u"Picture1 (required)"),upload_to='cloth/img',null=True,help_text=_(u'2MB Upload Limit'))
    picture2 = models.ImageField(_(u"Picture2 (optional)"),upload_to='cloth/img', blank=True,null=True,help_text=_(u'2MB Upload Limit'))
    item_code =models.CharField(max_length=20,blank=True)
    deleted = models.BooleanField(default=False)
    last_updated = models.DateTimeField(default=datetime.now)
    primary = models.BooleanField(default=False)
    set_primary_date= models.DateTimeField(default=datetime.now,null=True)
    slug = models.SlugField(null=True,blank=True)
    def description_list(self):
        description_list=self.description.split('\r')
        return description_list
    def __unicode__(self):
        return self.item
    def get_absolute_url(self):
        return reverse('detail_items',args=(self.pk,self.slug))
    def get_previous_item(self):
        item_in_line = Item.objects.filter(line=self.line)
        counter = 0 # counter for checking item position
        previous = ''
        for item in item_in_line:
            if item.id == self.id:
                if counter>0:
                    previous = item_in_line[counter-1]
                else:
                    previous = None
            counter +=1
        return previous

    def get_next_item(self):
        item_in_line = Item.objects.filter(line=self.line).order_by('id')
        counter = 0 # counter for checking item position
        next = ''
        for item in item_in_line:
            if item.id == self.id:
                if counter<item_in_line.count()-1:
                    next = item_in_line[counter+1]
                else:
                    next = None
            counter +=1
        return next
    
    def save(self):
        if self.item!='' and self.item!=' ':
            self.slug=slugify(self.item[:50])
        else:
            self.slug = "no-name"
        super(Item,self).save()

class Addicted(models.Model):
    user = models.ForeignKey(User)
    store = models.ForeignKey(Store)
    deleted=models.BooleanField(default=False)
    class Meta:
        unique_together=(('user','store'),)
    def __unicode__(self):
        return '%s' % (self.store)
    
class Comment(models.Model):
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item,null=True)
    store = models.ForeignKey(Store,null=True)
    comment = models.TextField()
    date_added = models.DateTimeField(default=datetime.now())
    def save(self,force_insert=False, force_update=False):
        self.comment = removetags(self.comment,'script')
        self.comment = removetags(self.comment,'iframe')
        self.comment = render_bbcode(mark_safe(self.comment))
        super(Comment,self).save(force_insert=force_insert,force_update=force_update)
    def __unicode__(self):
        return '%s' %(self.user)

class View(models.Model):
    store = models.ForeignKey(Store,null=True)
    item = models.ForeignKey(Item,null=True)
    count = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s %s %s' %(self.store,self.item,self.count)

class CommentNumber(models.Model):
    store = models.ForeignKey(Store,null=True)
    item = models.ForeignKey(Item,null=True)
    count = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s %s %s' %(self.store,self.item,self.count)

class Rating(models.Model):
    store = models.ForeignKey(Store,null=True)
    item = models.ForeignKey(Item,null=True)
    avg_rate = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s %s' %(self.store,self.item)

class RatingCounter(models.Model):
    user = models.ForeignKey(User)
    store = models.ForeignKey(Store,null=True)
    item = models.ForeignKey(Item,null=True)
    rate = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=date.today())
    def __unicode__(self):
        return '%s %s %s' %(self.user,self.store,self.item)
        

class Compare_List(models.Model):
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    deleted = models.BooleanField(default=False)
    class Meta:
        unique_together=(('user','item'),)
    def __unicode__(self):
        return '%s' %(self.item)
    
"""
class SearchFashionItemForm(ItemForm):
    category = forms.ModelChoiceField(Category.objects.all(),label=_(u'Category'))
    company_name = forms.ModelChoiceField(Store.objects.all(),label=_(u'Label'))
    class Meta(ItemForm.Meta):
        fields = [
                  'item',
                  'gender',
                  'category',
                  'company_name',
                  'availability',
                 ]
    def __init__(self, *args, **kwargs):
        super(SearchFashionItemForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = self.Meta.fields

"""        

templates/store/add_store.html
{%extends "account_base.html"%}
{%load i18n%}
{% block title %}
Fashionment.com - {%ifequal user.account_type 1 %}{% trans 'Add Your Own Online Store' %}{% else %}{% trans 'Add Portfolio to designers profile' %}{%endifequal%}
{% endblock %}
{%block content_loged%}
<div id="add_store_big_div">
<form method="POST" id="add_store_form"  enctype="multipart/form-data" >
    <div>
        <div class="title">
            <h2>{%ifequal user.account_type 1 %}{%trans 'Add your Store'%}{%else%}{%trans 'Add your Portfolio'%}{%endifequal%}</h2>
        </div>
        {%for field_add_store in add_store_form%}
            <div class="each_row" id="row{{forloop.counter}}">
                <div class="column2">
                    <div class="column1" id="columnb{{forloop.counter}}">
                        {{field_add_store.label}}
                    </div>
                    {{field_add_store}}
                    {{field_add_store.errors}}
                    <div class="eg" id="eg{{forloop.counter}}">
                        {{field_add_store.help_text}}
                    </div>
                </div>
            </div>
        {%endfor%}
        <div class="column2">
            <div class="column1">
            </div>
            <input class="short_red_button" type="submit" value="Submit"/>
        </div>
    </div>
</form>
</div>

<textarea class="location no_display" name="tb">{{user_data.street_address}}</textarea>
<script>
 <!--
$(document).ready(function(){
    $("#add_store_form").submitLoad()
    var address;
    if(!$.mobile()){
    $('textarea[name="tb"]').each(function(){
	      address =$(this).val()
    $("#columnb15").append('<a id="promotion_clickme" href="#"  title="Promotion Text|Promote your store now to get the chance of selling items fast. All promotional text you type here are viewable from homepage, but make sure you update it regularly as we only have limited space for promotional text."><img style="margin:3px 0 0 0;border:none;cursor:help;" src="{{MEDIA_URL}}/img/whats_this.png" /></a>')
    $('#promotion_clickme').cluetip({activation: 'click', sticky: true,closePosition: 'title', width: 350, splitTitle: '|'});
  })
  
  updateModel2({form:'#add_store_form',model:'#id_province',brand:'#id_country'})
  updateModel2({form:'#add_store_form',model:'#id_phone_area',brand:'#id_province'})
  updateModel2({form:'#add_store_form',model:'#id_fax_code',brand:'#id_province'})
  $('#id_checkbox').attr('style','margin-left:-150px;')
  $('#eg2').attr('style','margin-left:-130px; margin-top: -16px; font-size:13px; font-weight:bold;') 
  $('#row7').hide()
  $('#id_phone_area').insertAfter($('#columnb8'))
  $('#row10').hide()
  $('#columnb2').hide()
  $('#id_fax_code').insertAfter($('#columnb11'))
  $('#id_checkbox').click(function(){
        if (this.checked) {      //this.checked is NOT from jquery
            $("#id_country").val('{{user_data.country}}')
                if($('#id_country').val()=="1"){
                    $('#id_province').attr('disabled',false);
                    $('#id_phone_area').attr('disabled',false);
                    $('#id_fax_code').attr('disabled',false);
                    $('#fake_select').children().appendTo('#id_province')
                    $("#id_phone_area").val('{{user_data.phone_area_code}}')
                }
                if($('#id_country').val()!="1"){
                    $('#id_province').attr('disabled',true);
                    $('#id_phone_area').attr('disabled',true);
                    $('#id_fax_code').attr('disabled',true);
                }
            $("#id_location").val(address)
            $("#id_province").val('{{user_data.province}}')
            $("#id_post_code").val('{{user_data.post_code}}')
            
            $("#id_telephone").val('{{user_data.telephone}}')
            $("#id_handphone").val('{{user_data.handphone}}')
            $("#id_fax_code").val('{{user_data.fax_area_code}}')
            $("#id_fax").val('{{user_data.fax}}')
            $("#id_company_website").val('{{user_data.personal_website}}')
            //updateModel2({form:'#add_store_form',model:'#id_province',brand:'#id_country',temp_value:'{{user_data.province}}'});
            //alert('{{user_data.province}}')
        } else {
            $("#id_location").val('');
            $("#id_province").val('');
            $("#id_post_code").val('');
            $("#id_country").val('');
            $("#id_phone_area").val('');
            $("#id_telephone").val('');
            $("#id_handphone").val('');
            $("#id_fax_code").val('');
            $("#id_fax").val('');
            $("#id_company_website").val('');
            $('#id_province').attr('disabled',true)
         }
    });
        $('#id_telephone').numeric({allow:"+"});
        $('#id_post_code').numeric();
        $('#id_handphone').numeric({allow:"+"});
        $('#id_fax').numeric({allow:"+"});
        $('#id_country').change(function(){
            if($(this).val()=="1"){
                $('#id_province').attr('disabled',false);
                $('#id_phone_area').attr('disabled',false);
                $('#id_fax_code').attr('disabled',false);
            }else{
                $('#id_province').attr('disabled',true);
                $('#id_phone_area').attr('disabled',true);
                $('#id_fax_code').attr('disabled',true);
            }
        })
        fieldlimiter.setup({
            thefield: document.getElementById("id_location"), //reference to form field
            maxlength: 100,
            statusids: ["eg3"], //id(s) of divs to output characters limit. If non, set to empty array [].
            onkeypress:function(maxlength, curlength){ //onkeypress event handler
                //define custom event actions here if desired
            }
        })
        fieldlimiter.setup({
            thefield: document.getElementById("id_store_story"), //reference to form field
            maxlength: 1000,
            statusids: ["eg13"], //id(s) of divs to output characters limit. If non, set to empty array [].
            onkeypress:function(maxlength, curlength){ //onkeypress event handler
                //define custom event actions here if desired
            }
        })
        fieldlimiter.setup({
            thefield: document.getElementById("id_promotion_text"), //reference to form field
            maxlength: 1000,
            statusids: ["eg15"], //id(s) of divs to output characters limit. If non, set to empty array [].
            onkeypress:function(maxlength, curlength){ //onkeypress event handler
                //define custom event actions here if desired
            }
        })
        }
});

-->
</script>
{%endblock%}

templates/store/addicts_to.html
{%extends "account_base.html"%}
{%load i18n%}
{%load thumbnail%}
{% block title %}
Fashionment.com - {% trans 'Addicts To' %}
{% endblock %}
{%block content_loged%}
<div class="form_fields">
    <div class="detail_comp big_bottom_marg">
       <a href="{% url view_my_profile %}" class="hyperlink">{% trans 'My Profile' %} > </a> {%trans 'I Addicted To'%}
    </div>
    <div class="title small_bottom_space activate">
        {%trans 'I addicted To'%}
    </div>
    {%if addicts_to%}
    {%for fan_to in addicts_to%}
    <div class="rows fan_to_div">
        <div class="mail_tab_unselected smallest_bottom_min_marg">
            {{fan_to}}
        </div>

        <div class="view_picture">
            <a href="{%url view_stores fan_to.store.slug%}"  ><div class="addicted_div addicted_div_marg" style="{% if fan_to.store.picture %}background-image:url({% thumbnail fan_to.store.picture.name 120x80 %});{% endif %}"></div></a>
            <a href="{%url remove_addict fan_to.id%}" >{%trans 'Remove'%}</a>
        </div>
    </div>
    {%endfor%}
    {%else%}
        {%blocktrans%}
            You are not an addiction just yet. Make people addict to you by increasing your collections and doing more promotions
        {%endblocktrans%}
    {%endif%}
</div>

{%endblock%}

templates/store/my_addicts.html
{%extends "account_base.html"%}
{%load i18n%}
{%load thumbnail%}
{% block title %}
Fashionment.com - {% trans 'My Addicts' %}
{% endblock %}
{%block content_loged%}
{%for my_fan in my_addict%}
    {%for store_fan in my_fan.user.store_set.all%}
        <div class="rows" style="float:left;">
            {{store_fan}}
            <div class="view_picture">
                <div class="addicted_div addicted_div_margin" style="{% if store_fan.picture %}background-image:url({% thumbnail store_fan.picture.name 120x80 %});{% endif %}"></div>
            </div>
        </div>
    {%endfor%}
{%endfor%}
{%endblock%}

templates/store/search_designer_form.html
{% load i18n %}
{% load cache %}
    {% cache 3600 search_designer_form %}
     <div id="search_designer_form_box" class="search_form_box">
          <form method="GET" id="search_designer_form" action="{% url list_designer %}">
            <table>
                 {% for field in form %}
                <tr>
                    <td width="22%">
                        {% ifequal field.label "Search Stores"%}
                            {% trans 'Search Designer'%}
                        {%else%}
                            {% ifequal field.label "Line" %}
                                {% trans 'Collection ' %}
                            {% else %}
                                {{ field.label }}
                            {% endifequal %}
                        {%endifequal%}
                        :
                    </td>
                    <td width="76%">
                        {{ field }}
                    </td>
                </tr>
                 {% endfor %}
                 <tr style="height:25px;">
                    <td width="22%">
                        &nbsp;
                    </td>
                    <td width="76%">
                        &nbsp;
                    </td>
                </tr>
                 <tr>
                     <td colspan="5" align="right">
                            <input class="short_red_button" style="padding:1px 11px 4px;" type="submit" value="search" name="submit" />
                     </td>
                 </tr>
            </table>
          </form>
        </div>
        {% endcache %}
<script>
    <!--
    $(document).ready(function(){
        $("[name=keyword]").css('width','450px')
        updateModel3({form:'#search_designer_form',model:'#id_line',brand:'#id_category'})
    })
    -->
</script>

templates/store/search_store_form.html
{% load i18n %}   
     <div id="search_store_form_box" class="search_form_box">
          <form method="GET" id="search_store_form" action="{% url list_store %}">
            <table>
                 {% for field in form %}
                <tr>
                    <td width="22%">
                        {% ifequal field.label "Line" %}
                        {% trans 'Collection ' %}
                        {% else %}
                        {{ field.label }} 
                        {% endifequal %}
                        :
                    </td>
                    <td width="76%">
                        {{ field }}
                    </td>
                </tr>
                 {% endfor %}
                 <tr style="height:25px;">
                    <td width="22%">
                        &nbsp;
                    </td>
                    <td width="76%">
                        &nbsp;
                    </td>
                </tr>
                 <tr>
                     <td colspan="5" align="right">
                            <input class="short_red_button" style="padding:1px 11px 4px;" type="submit" value="search" name="submit" />
                     </td>
                 </tr>
            </table>
          </form>
        </div>
<script>
    <!--
    $(document).ready(function(){
        $("#id_keyword").css('width','450px')
        updateModel3({form:'#search_store_form',model:'#id_line',brand:'#id_category'})
    })
    -->
</script>